insert into product (name, quantity, price) values ('Wine - Barossa Valley Estate', 18, 20);
insert into product (name, quantity, price) values ('Beer - Paulaner Hefeweisse', 13, 57);
insert into product (name, quantity, price) values ('Crush - Grape, 355 Ml', 10, 31);
insert into product (name, quantity, price) values ('Beer - Steamwhistle', 19, 63);
insert into product (name, quantity, price) values ('Cake - Bande Of Fruit', 2, 51);
insert into product (name, quantity, price) values ('Oil - Canola', 4, 96);
insert into product (name, quantity, price) values ('Beef - Striploin Aa', 20, 38);
insert into product (name, quantity, price) values ('Creme De Banane - Marie', 1, 48);
insert into product (name, quantity, price) values ('Oil - Shortening,liqud, Fry', 3, 89);
insert into product (name, quantity, price) values ('Potatoes - Mini Red', 14, 59);
insert into product (name, quantity, price) values ('Wine - Niagara Peninsula Vqa', 20, 21);
insert into product (name, quantity, price) values ('Cranberry Foccacia', 10, 84);
insert into product (name, quantity, price) values ('Ice Cream Bar - Drumstick', 7, 57);
insert into product (name, quantity, price) values ('Grapes - Green', 6, 62);
insert into product (name, quantity, price) values ('Wine - Champagne Brut Veuve', 7, 33);
insert into product (name, quantity, price) values ('Stainless Steel Cleaner Vision', 5, 51);
insert into product (name, quantity, price) values ('Pastry - Chocolate Chip Muffin', 16, 16);
insert into product (name, quantity, price) values ('Cheese - Feta', 14, 16);
insert into product (name, quantity, price) values ('Nestea - Iced Tea', 18, 72);
insert into product (name, quantity, price) values ('Cheese - Brie,danish', 8, 63);
insert into product (name, quantity, price) values ('Hog / Sausage Casing - Pork', 15, 83);
insert into product (name, quantity, price) values ('Whmis - Spray Bottle Trigger', 4, 54);
insert into product (name, quantity, price) values ('Bread - Granary Small Pull', 12, 13);
insert into product (name, quantity, price) values ('Irish Cream - Butterscotch', 19, 97);
insert into product (name, quantity, price) values ('Tomatoes Tear Drop', 7, 33);
insert into product (name, quantity, price) values ('Cake - Sheet Strawberry', 14, 33);
insert into product (name, quantity, price) values ('Petit Baguette', 12, 61);
insert into product (name, quantity, price) values ('Capon - Breast, Wing On', 10, 96);
insert into product (name, quantity, price) values ('Cheese - Le Cru Du Clocher', 10, 67);
insert into product (name, quantity, price) values ('Onions - Vidalia', 2, 12);
insert into product (name, quantity, price) values ('Chicken - Tenderloin', 15, 33);
insert into product (name, quantity, price) values ('Roe - Lump Fish, Red', 10, 23);
insert into product (name, quantity, price) values ('Cheese - Manchego, Spanish', 19, 69);
insert into product (name, quantity, price) values ('Fireball Whisky', 10, 57);
insert into product (name, quantity, price) values ('Potatoes - Peeled', 1, 69);
insert into product (name, quantity, price) values ('Cheese - Cheddarsliced', 16, 37);
insert into product (name, quantity, price) values ('Appetizer - Chicken Satay', 20, 32);
insert into product (name, quantity, price) values ('Red Cod Fillets - 225g', 20, 76);
insert into product (name, quantity, price) values ('Chocolate - Semi Sweet, Calets', 16, 14);
insert into product (name, quantity, price) values ('Foil - Round Foil', 15, 90);
insert into product (name, quantity, price) values ('Tomatoes - Roma', 2, 41);
insert into product (name, quantity, price) values ('Island Oasis - Mango Daiquiri', 5, 80);
insert into product (name, quantity, price) values ('Wine - Winzer Krems Gruner', 8, 13);
insert into product (name, quantity, price) values ('Lentils - Green Le Puy', 10, 22);
insert into product (name, quantity, price) values ('Flour - Semolina', 1, 82);
insert into product (name, quantity, price) values ('Icecream Bar - Del Monte', 15, 63);
insert into product (name, quantity, price) values ('Ecolab - Orange Frc, Cleaner', 7, 32);
insert into product (name, quantity, price) values ('Dome Lid Clear P92008h', 8, 21);
insert into product (name, quantity, price) values ('Corn Shoots', 1, 51);
insert into product (name, quantity, price) values ('Stock - Veal, Brown', 5, 60);
insert into product (name, quantity, price) values ('Veal - Nuckle', 2, 94);
insert into product (name, quantity, price) values ('Sugar - Splenda Sweetener', 16, 79);
insert into product (name, quantity, price) values ('Crackers - Soda / Saltins', 5, 63);
insert into product (name, quantity, price) values ('Sprouts - Baby Pea Tendrils', 14, 86);
insert into product (name, quantity, price) values ('Bread - Burger', 19, 76);
insert into product (name, quantity, price) values ('Ecolab - Medallion', 15, 59);
insert into product (name, quantity, price) values ('Pasta - Shells, Medium, Dry', 10, 91);
insert into product (name, quantity, price) values ('Oil - Olive', 17, 99);
insert into product (name, quantity, price) values ('Veal - Leg, Provimi - 50 Lb Max', 12, 92);
insert into product (name, quantity, price) values ('Sauce - Hollandaise', 17, 64);
insert into product (name, quantity, price) values ('Beer - Mill St Organic', 2, 61);
insert into product (name, quantity, price) values ('Cheese - Brie, Cups 125g', 16, 20);
insert into product (name, quantity, price) values ('C - Plus, Orange', 1, 13);
insert into product (name, quantity, price) values ('Muffin - Mix - Bran And Maple 15l', 2, 32);
insert into product (name, quantity, price) values ('Mayonnaise', 1, 74);
insert into product (name, quantity, price) values ('Soup - Base Broth Chix', 12, 16);
insert into product (name, quantity, price) values ('Gin - Gilbeys London, Dry', 7, 85);
insert into product (name, quantity, price) values ('Pasta - Canelloni, Single Serve', 4, 50);
insert into product (name, quantity, price) values ('Wine - White, Ej Gallo', 16, 99);
insert into product (name, quantity, price) values ('Chips - Assorted', 9, 93);
insert into product (name, quantity, price) values ('Beef - Baby, Liver', 6, 47);
insert into product (name, quantity, price) values ('Pepper - White, Whole', 20, 29);
insert into product (name, quantity, price) values ('Cheese - Swiss', 6, 92);
insert into product (name, quantity, price) values ('Blackberries', 12, 85);
insert into product (name, quantity, price) values ('Wine - Muscadet Sur Lie', 4, 26);
insert into product (name, quantity, price) values ('Cheese - Camembert', 19, 26);
insert into product (name, quantity, price) values ('Pastry - Mini French Pastries', 7, 38);
insert into product (name, quantity, price) values ('Chevere Logs', 20, 17);
insert into product (name, quantity, price) values ('Olive - Spread Tapenade', 3, 10);
insert into product (name, quantity, price) values ('Durian Fruit', 20, 85);
insert into product (name, quantity, price) values ('Foil Wrap', 4, 99);
insert into product (name, quantity, price) values ('Container - Clear 16 Oz', 1, 42);
insert into product (name, quantity, price) values ('Wine - Pinot Grigio Collavini', 4, 57);
insert into product (name, quantity, price) values ('Beans - Kidney, Red Dry', 1, 58);
insert into product (name, quantity, price) values ('Wine - Mondavi Coastal Private', 17, 91);
insert into product (name, quantity, price) values ('Capon - Whole', 20, 49);
insert into product (name, quantity, price) values ('Coffee - Colombian, Portioned', 9, 85);
insert into product (name, quantity, price) values ('Gelatine Powder', 2, 18);
insert into product (name, quantity, price) values ('Raisin - Dark', 16, 58);
insert into product (name, quantity, price) values ('Wine - Charddonnay Errazuriz', 4, 31);
insert into product (name, quantity, price) values ('Wasabi Paste', 9, 15);
insert into product (name, quantity, price) values ('Chervil - Fresh', 14, 17);
insert into product (name, quantity, price) values ('Appetizer - Sausage Rolls', 4, 71);
insert into product (name, quantity, price) values ('Cheese - Brick With Pepper', 1, 13);
insert into product (name, quantity, price) values ('Persimmons', 1, 89);
insert into product (name, quantity, price) values ('Bar - Sweet And Salty Chocolate', 17, 98);
insert into product (name, quantity, price) values ('Cherries - Bing, Canned', 15, 29);
insert into product (name, quantity, price) values ('Trout Rainbow Whole', 19, 68);
insert into product (name, quantity, price) values ('Energy Drink', 6, 28);
insert into product (name, quantity, price) values ('Apple - Macintosh', 11, 39);